version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: price-tracker-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: price_tracker
      POSTGRES_USER: price_tracker_user
      POSTGRES_PASSWORD: price_tracker_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - price-tracker-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U price_tracker_user -d price_tracker"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgreSQL Test Database
  postgres-test:
    image: postgres:15-alpine
    container_name: price-tracker-postgres-test
    restart: unless-stopped
    environment:
      POSTGRES_DB: price_tracker_test
      POSTGRES_USER: price_tracker_user
      POSTGRES_PASSWORD: price_tracker_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - price-tracker-network
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U price_tracker_user -d price_tracker_test"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: price-tracker-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - price-tracker-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin for database management (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: price-tracker-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pricetracker.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - price-tracker-network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  postgres_test_data:
  redis_data:
  pgadmin_data:

networks:
  price-tracker-network:
    driver: bridge
