version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: pricepulse-postgres
    environment:
      POSTGRES_DB: pricepulse
      POSTGRES_USER: pricepulse
      POSTGRES_PASSWORD: pricepulse123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pricepulse-network

  postgres-test:
    image: postgres:15-alpine
    container_name: pricepulse-postgres-test
    environment:
      POSTGRES_DB: pricepulse_test
      POSTGRES_USER: pricepulse
      POSTGRES_PASSWORD: pricepulse123
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - pricepulse-network

  redis:
    image: redis:7-alpine
    container_name: pricepulse-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pricepulse-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pricepulse-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pricepulse.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - pricepulse-network
    depends_on:
      - postgres

volumes:
  postgres_data:
  postgres_test_data:
  redis_data:
  pgadmin_data:

networks:
  pricepulse-network:
    driver: bridge
