[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "cd backend && npm install --production --no-optional --no-audit --prefer-offline --no-fund --no-license --maxsockets=1 --progress=false",
]

[phases.build]
cmds = [
  "cd backend && npm run build",
  "mkdir -p backend/dist/public",
  "echo '<html><head><title>ShopperSprint - Coming Soon</title><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><style>body{font-family:system-ui,sans-serif;margin:0;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:white;text-align:center;padding:2rem}.container{max-width:600px;margin:0 auto;padding:2rem;background:rgba(255,255,255,0.1);border-radius:20px;backdrop-filter:blur(10px)}.logo{font-size:3rem;margin-bottom:1rem}.title{font-size:2rem;margin-bottom:1rem}.subtitle{font-size:1.2rem;margin-bottom:2rem;opacity:0.9}.email-form{display:flex;gap:1rem;margin-bottom:1rem;flex-wrap:wrap;justify-content:center}.email-input{padding:1rem;border:none;border-radius:10px;font-size:1rem;flex:1;min-width:200px}.btn{padding:1rem 2rem;background:#ff6b6b;color:white;border:none;border-radius:10px;font-size:1rem;cursor:pointer;transition:all 0.3s}.btn:hover{background:#ff5252;transform:translateY(-2px)}</style></head><body><div class=\"container\"><div class=\"logo\">🛒 ShopperSprint</div><h1 class=\"title\">Coming Soon</h1><p class=\"subtitle\">Canada\\'s smartest price comparison platform is launching soon!</p><form class=\"email-form\" action=\"/api/waitlist/subscribe\" method=\"post\"><input type=\"email\" name=\"email\" placeholder=\"Enter your email\" class=\"email-input\" required><button type=\"submit\" class=\"btn\">Join Waitlist</button></form><p>Track prices • Find deals • Save money</p></div></body></html>' > backend/dist/public/index.html",
]

[start]
cmd = "cd backend && node dist/index.js"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
