[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "npm ci --prefer-offline --no-audit --no-fund --silent",
  "cd backend && PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm ci --prefer-offline --no-audit --no-fund --only=production --silent",
  "cd frontend && npm ci --prefer-offline --no-audit --no-fund --only=production --silent"
]

[variables]
NODE_ENV = "production"
SERVE_FRONTEND = "true"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
NPM_CONFIG_LOGLEVEL = "error"
