[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "cd backend && npm ci --only=production --silent",
  "cd frontend && npm ci --only=production --silent"
]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "mkdir -p backend/dist/public",
  "cp -r frontend/dist/* backend/dist/public/",
  "cd backend && npm run build"
]

[start]
cmd = "cd backend && node dist/index.js"

[variables]
NODE_ENV = "production"
SERVE_FRONTEND = "true"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
