[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "npm install --no-audit --no-fund",
  "cd backend && npm install --no-audit --no-fund",
  "cd frontend && npm install --no-audit --no-fund"
]

[phases.build]
cmds = [
  "cd backend && npm run build",
  "cd frontend && npm run build",
  "mkdir -p backend/dist/public",
  "cp -r frontend/dist/* backend/dist/public/"
]

[start]
cmd = "cd backend && node dist/index.js"

[variables]
NODE_ENV = "production"
SERVE_FRONTEND = "true"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
