# Nixpacks configuration for Railway frontend-only deployment
# Use this when deploying frontend as a separate service

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = ["npm ci", "cd frontend && npm ci"]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "cd frontend && npm run preview"

[variables]
NODE_ENV = "production"
