# Nixpacks configuration for Railway deployment
# This configuration deploys backend + frontend as a single service

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = ["npm ci", "cd backend && npm ci", "cd frontend && npm ci"]

[phases.build]
cmds = [
    # Build frontend first
    "cd frontend && npm run build",
    # Build backend
    "cd backend && npm run build",
    # Copy frontend build to backend public directory
    "mkdir -p backend/dist/public",
    "cp -r frontend/dist/* backend/dist/public/",
]

[start]
cmd = "cd backend && npm start"

[variables]
# Railway will set PORT automatically
NODE_ENV = "production"
SERVE_FRONTEND = "true"
