name: Deploy to Production
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "production"
        type: choice
        options:
          - production
          - staging

env:
  NODE_ENV: production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Check environment
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "🚀 Production deployment triggered"
          else
            echo "🧪 Staging deployment triggered"
          fi

      - name: Install dependencies
        run: |
          npm ci
          cd frontend && npm ci
          cd ../backend && npm ci

      - name: Run tests
        run: |
          npm run test:backend
          npm run test:frontend

      - name: Build application
        run: |
          npm run build:backend
          npm run build:frontend

      - name: Setup production database
        run: |
          cd backend
          npm run db:setup:prod
        env:
          NODE_ENV: production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}

      - name: Deploy to production server
        run: |
          echo "🚀 Deploying to production server..."
          # Add your deployment commands here
          # Examples:
          # - rsync to server
          # - Docker deployment
          # - Cloud platform deployment

      - name: Health check
        run: |
          echo "🏥 Running health check..."
          # Add health check commands here
          # Wait for deployment and verify it's working

      - name: Notify deployment status
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "✅ Deployment successful!"
          else
            echo "❌ Deployment failed!"
          fi
