name: Deploy to Railway (Official Action)

on:
  push:
    branches: [ coming-soon ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Railway
      uses: railway/cli@v3
      with:
        command: up --detach
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
